/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.right[_ngcontent-%COMP%] {\n  float: right;\n}\n.navbar[_ngcontent-%COMP%] {\n  background-color: #583123;\n  width: 100%;\n  color:white;\n  position: fixed;\n  top: 0;\n  left: 0;\n  ul {\n    width: 100%;\n    list-style-type: none;\n    overflow: hidden;\n    margin: 0;\n    // margin: auto;\n    padding: 0;\n    li {\n      @media screen and (max-width: 480px) {\n        display: none;\n      }\n      float: left;\n      a {\n        text-align: center;\n        display: block;\n        color: white;\n        text-decoration: none;\n        padding: 16px 25px;\n        transition: 0.3s linear;\n        &:hover {\n          transition: 0.3s linear;\n          background-color: white;\n          color: #583123;\n          cursor: pointer;\n        }\n      }\n    }\n  }\n}\n\n.active[_ngcontent-%COMP%] {\n  background-color: white;\n  color: #583123 !important;\n}\n\n.pad-top[_ngcontent-%COMP%] {\n  height: 50px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvem0vTXlQcm9qZWN0cy9tZWFuNC9zcmMvYXBwL2NvbXBvbmVudHMvbmF2YmFyL25hdmJhci5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3ptL015UHJvamVjdHMvbWVhbjQvc3JjL2FwcC9jb21wb25lbnRzL25hdmJhci9uYXZiYXIuY29tcG9uZW50LnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
