/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './stock-income.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../../../src/app/components/stock/stock-income/stock-income.component';
const styles_StockIncomeComponent:any[] = [i0.styles];
export const RenderType_StockIncomeComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_StockIncomeComponent,data:{}});
export function View_StockIncomeComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  stock-income works!\n'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_StockIncomeComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'stock-income',
      ([] as any[]),(null as any),(null as any),(null as any),View_StockIncomeComponent_0,
      RenderType_StockIncomeComponent)),i1.ɵdid(114688,(null as any),0,i2.StockIncomeComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const StockIncomeComponentNgFactory:i1.ComponentFactory<i2.StockIncomeComponent> = i1.ɵccf('stock-income',
    i2.StockIncomeComponent,View_StockIncomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvem0vTXlQcm9qZWN0cy9tZWFuNC9zcmMvYXBwL2NvbXBvbmVudHMvc3RvY2svc3RvY2staW5jb21lL3N0b2NrLWluY29tZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS96bS9NeVByb2plY3RzL21lYW40L3NyYy9hcHAvY29tcG9uZW50cy9zdG9jay9zdG9jay1pbmNvbWUvc3RvY2staW5jb21lLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvem0vTXlQcm9qZWN0cy9tZWFuNC9zcmMvYXBwL2NvbXBvbmVudHMvc3RvY2svc3RvY2staW5jb21lL3N0b2NrLWluY29tZS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvem0vTXlQcm9qZWN0cy9tZWFuNC9zcmMvYXBwL2NvbXBvbmVudHMvc3RvY2svc3RvY2staW5jb21lL3N0b2NrLWluY29tZS5jb21wb25lbnQudHMuU3RvY2tJbmNvbWVDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cbiAgc3RvY2staW5jb21lIHdvcmtzIVxuPC9wPlxuIiwiPHN0b2NrLWluY29tZT48L3N0b2NrLWluY29tZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLCtDQUVDO01BQUE7OztvQkNGSjtNQUFBO3FDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
