/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from './components/create-stock/create-stock.component.ngfactory';
import * as i4 from './components/main-stock/main-stock.component.ngfactory';
import * as i5 from './components/catalog/catalog.component.ngfactory';
import * as i6 from './components/production/production.component.ngfactory';
import * as i7 from './components/stock/stock.component.ngfactory';
import * as i8 from '../../node_modules/@angular/material/typings/index.ngfactory';
import * as i9 from './app.component.ngfactory';
import * as i10 from '@angular/common';
import * as i11 from '@angular/platform-browser';
import * as i12 from '@angular/material';
import * as i13 from '@angular/animations/browser';
import * as i14 from '@angular/platform-browser/animations';
import * as i15 from '@angular/router';
import * as i16 from '@angular/http';
import * as i17 from '@angular/cdk/bidi';
import * as i18 from '@angular/cdk/platform';
import * as i19 from '@angular/cdk/scrolling';
import * as i20 from '@angular/cdk/overlay';
import * as i21 from '@angular/cdk/observers';
import * as i22 from '@angular/cdk/a11y';
import * as i23 from '@angular/animations';
import * as i24 from '@angular/forms';
import * as i25 from './services/stock.service';
import * as i26 from 'angular-font-awesome/index';
import * as i27 from './components/create-stock/create-stock.component';
import * as i28 from './components/main-stock/main-stock.component';
import * as i29 from './components/catalog/catalog.component';
import * as i30 from './components/production/production.component';
import * as i31 from './components/stock/stock.component';
import * as i32 from './app-routing.module';
import * as i33 from '@angular/cdk/portal';
import * as i34 from '@angular/cdk/table';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.CreateStockComponentNgFactory,i4.MainStockComponentNgFactory,i5.CatalogComponentNgFactory,
              i6.ProductionComponentNgFactory,i7.StockComponentNgFactory,i8.MdDialogContainerNgFactory,
              i8.MdDatepickerContentNgFactory,i8.TooltipComponentNgFactory,i8.MdSnackBarContainerNgFactory,
              i8.SimpleSnackBarNgFactory,i9.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),
          i0.ɵmpd(4608,i10.NgLocalization,i10.NgLocaleLocalization,[i0.LOCALE_ID]),
          i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,
              i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),
          i0.ɵmpd(4608,i11.DomSanitizer,i11.ɵe,[i10.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,
              (null as any),[i11.DomSanitizer]),i0.ɵmpd(4608,i11.HAMMER_GESTURE_CONFIG,
              i12.GestureConfig,([] as any[])),i0.ɵmpd(5120,i11.EVENT_MANAGER_PLUGINS,
              (p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i11.ɵDomEventsPlugin(p0_0),new i11.ɵKeyEventsPlugin(p1_0),
                    new i11.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i10.DOCUMENT,i10.DOCUMENT,i10.DOCUMENT,i11.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i11.EventManager,i11.EventManager,[i11.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i11.ɵDomSharedStylesHost,i11.ɵDomSharedStylesHost,
              [i10.DOCUMENT]),i0.ɵmpd(4608,i11.ɵDomRendererFactory2,i11.ɵDomRendererFactory2,
              [i11.EventManager,i11.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i13.AnimationDriver,
              i14.ɵc,([] as any[])),i0.ɵmpd(5120,i13.ɵAnimationStyleNormalizer,i14.ɵd,
              ([] as any[])),i0.ɵmpd(4608,i13.ɵAnimationEngine,i14.ɵb,[i13.AnimationDriver,
              i13.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i14.ɵe,
              [i11.ɵDomRendererFactory2,i13.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i11.ɵSharedStylesHost,(null as any),[i11.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i11.Meta,i11.Meta,
              [i10.DOCUMENT]),i0.ɵmpd(4608,i11.Title,i11.Title,[i10.DOCUMENT]),i0.ɵmpd(5120,
              i15.ActivatedRoute,i15.ɵf,[i15.Router]),i0.ɵmpd(4608,i15.NoPreloading,
              i15.NoPreloading,([] as any[])),i0.ɵmpd(6144,i15.PreloadingStrategy,
              (null as any),[i15.NoPreloading]),i0.ɵmpd(135680,i15.RouterPreloader,
              i15.RouterPreloader,[i15.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i15.PreloadingStrategy]),i0.ɵmpd(4608,i15.PreloadAllModules,
              i15.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i15.ROUTER_INITIALIZER,
              i15.ɵi,[i15.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i15.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i16.BrowserXhr,i16.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i16.ResponseOptions,i16.BaseResponseOptions,([] as any[])),
          i0.ɵmpd(5120,i16.XSRFStrategy,i16.ɵb,([] as any[])),i0.ɵmpd(4608,i16.XHRBackend,
              i16.XHRBackend,[i16.BrowserXhr,i16.ResponseOptions,i16.XSRFStrategy]),
          i0.ɵmpd(4608,i16.RequestOptions,i16.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i16.Http,i16.ɵc,[i16.XHRBackend,i16.RequestOptions]),i0.ɵmpd(6144,i17.DIR_DOCUMENT,
              (null as any),[i11.DOCUMENT]),i0.ɵmpd(4608,i17.Directionality,i17.Directionality,
              [[2,i17.DIR_DOCUMENT]]),i0.ɵmpd(4608,i18.Platform,i18.Platform,([] as any[])),
          i0.ɵmpd(5120,i19.ScrollDispatcher,i19.SCROLL_DISPATCHER_PROVIDER_FACTORY,
              [[3,i19.ScrollDispatcher],i0.NgZone,i18.Platform]),i0.ɵmpd(5120,i19.ViewportRuler,
              i19.VIEWPORT_RULER_PROVIDER_FACTORY,[[3,i19.ViewportRuler],i19.ScrollDispatcher]),
          i0.ɵmpd(4608,i20.ScrollStrategyOptions,i20.ScrollStrategyOptions,[i19.ScrollDispatcher,
              i19.ViewportRuler]),i0.ɵmpd(5120,i20.OverlayContainer,i20.ɵa,[[3,i20.OverlayContainer]]),
          i0.ɵmpd(4608,i20.ɵf,i20.ɵf,[i19.ViewportRuler]),i0.ɵmpd(4608,i20.Overlay,
              i20.Overlay,[i20.ScrollStrategyOptions,i20.OverlayContainer,i0.ComponentFactoryResolver,
                  i20.ɵf,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i20.ɵc,
              i20.ɵd,[i20.Overlay]),i0.ɵmpd(5120,i12.MD_AUTOCOMPLETE_SCROLL_STRATEGY,
              i12.MD_AUTOCOMPLETE_SCROLL_STRATEGY_PROVIDER_FACTORY,[i20.Overlay]),
          i0.ɵmpd(5120,i12.FocusOriginMonitor,i12.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,
              [[3,i12.FocusOriginMonitor],i0.NgZone,i18.Platform]),i0.ɵmpd(5120,i12.UniqueSelectionDispatcher,
              i12.ɵb,[[3,i12.UniqueSelectionDispatcher]]),i0.ɵmpd(4608,i21.MdMutationObserverFactory,
              i21.MdMutationObserverFactory,([] as any[])),i0.ɵmpd(4608,i22.InteractivityChecker,
              i22.InteractivityChecker,[i18.Platform]),i0.ɵmpd(4608,i22.FocusTrapFactory,
              i22.FocusTrapFactory,[i22.InteractivityChecker,i18.Platform,i0.NgZone]),
          i0.ɵmpd(5120,i22.LiveAnnouncer,i22.LIVE_ANNOUNCER_PROVIDER_FACTORY,[[3,i22.LiveAnnouncer],
              [2,i22.LIVE_ANNOUNCER_ELEMENT_TOKEN],i18.Platform]),i0.ɵmpd(5120,i12.MD_DIALOG_SCROLL_STRATEGY,
              i12.MD_DIALOG_SCROLL_STRATEGY_PROVIDER_FACTORY,[i20.Overlay]),i0.ɵmpd(4608,
              i12.MdDialog,i12.MdDialog,[i20.Overlay,i0.Injector,i12.MD_DIALOG_SCROLL_STRATEGY,
                  [2,i10.Location],[3,i12.MdDialog]]),i0.ɵmpd(5120,i12.MdIconRegistry,
              i12.ICON_REGISTRY_PROVIDER_FACTORY,[[3,i12.MdIconRegistry],[2,i16.Http],
                  i11.DomSanitizer]),i0.ɵmpd(4608,i12.MdDatepickerIntl,i12.MdDatepickerIntl,
              ([] as any[])),i0.ɵmpd(5120,i12.MD_DATEPICKER_SCROLL_STRATEGY,i12.MD_DATEPICKER_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i20.Overlay]),i0.ɵmpd(5120,i12.ɵl,i12.ɵm,[i20.Overlay]),i0.ɵmpd(5120,
              i12.MD_SELECT_SCROLL_STRATEGY,i12.MD_SELECT_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i20.Overlay]),i0.ɵmpd(5120,i12.MD_TOOLTIP_SCROLL_STRATEGY,i12.MD_TOOLTIP_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i20.Overlay]),i0.ɵmpd(4608,i12.MdPaginatorIntl,i12.MdPaginatorIntl,
              ([] as any[])),i0.ɵmpd(4608,i12.MdSnackBar,i12.MdSnackBar,[i20.Overlay,
              i22.LiveAnnouncer,i0.Injector,[3,i12.MdSnackBar]]),i0.ɵmpd(4608,i12.MdSortHeaderIntl,
              i12.MdSortHeaderIntl,([] as any[])),i0.ɵmpd(4608,i23.AnimationBuilder,
              i14.ɵBrowserAnimationBuilder,[i0.RendererFactory2]),i0.ɵmpd(4608,i24.ɵi,
              i24.ɵi,([] as any[])),i0.ɵmpd(4608,i24.FormBuilder,i24.FormBuilder,([] as any[])),
          i0.ɵmpd(4608,i25.StockService,i25.StockService,[i16.Http]),i0.ɵmpd(512,i10.CommonModule,
              i10.CommonModule,([] as any[])),i0.ɵmpd(512,i26.AngularFontAwesomeModule,
              i26.AngularFontAwesomeModule,([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,
              i11.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,() => {
            return [i15.ɵb()];
          },([] as any[])),i0.ɵmpd(512,i15.ɵg,i15.ɵg,[i0.Injector]),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any,p0_1:any,p1_0:any) => {
                return [i11.ɵc(p0_0,p0_1),i15.ɵh(p1_0)];
              },[[2,i11.NgProbeToken],[2,i0.NgProbeToken],i15.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i11.BrowserModule,i11.BrowserModule,[[3,i11.BrowserModule]]),
          i0.ɵmpd(1024,i15.ɵa,i15.ɵd,[[3,i15.Router]]),i0.ɵmpd(512,i15.UrlSerializer,
              i15.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i15.ChildrenOutletContexts,
              i15.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i15.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i10.LocationStrategy,i15.ɵc,[i10.PlatformLocation,
              [2,i10.APP_BASE_HREF],i15.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i10.Location,
              i10.Location,[i10.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i15.ROUTES,
              () => {
                return [[{path:'',redirectTo:'/create',pathMatch:'full'},{path:'create',
                    component:i27.CreateStockComponent},{path:'main',component:i28.MainStockComponent},
                    {path:'catalog',component:i29.CatalogComponent},{path:'production',
                        component:i30.ProductionComponent},{path:'stock',component:i31.StockComponent}]];
              },([] as any[])),i0.ɵmpd(1024,i15.Router,i15.ɵe,[i0.ApplicationRef,i15.UrlSerializer,
              i15.ChildrenOutletContexts,i10.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i15.ROUTES,i15.ROUTER_CONFIGURATION,[2,i15.UrlHandlingStrategy],
              [2,i15.RouteReuseStrategy]]),i0.ɵmpd(512,i15.RouterModule,i15.RouterModule,
              [[2,i15.ɵa],[2,i15.Router]]),i0.ɵmpd(512,i32.AppRoutingModule,i32.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i16.HttpModule,i16.HttpModule,([] as any[])),
          i0.ɵmpd(512,i12.CompatibilityModule,i12.CompatibilityModule,([] as any[])),
          i0.ɵmpd(512,i17.BidiModule,i17.BidiModule,([] as any[])),i0.ɵmpd(256,i12.MATERIAL_SANITY_CHECKS,
              true,([] as any[])),i0.ɵmpd(512,i12.MdCommonModule,i12.MdCommonModule,
              [[2,i11.DOCUMENT],[2,i12.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i18.PlatformModule,
              i18.PlatformModule,([] as any[])),i0.ɵmpd(512,i19.ScrollDispatchModule,
              i19.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,i12.MdRippleModule,
              i12.MdRippleModule,([] as any[])),i0.ɵmpd(512,i12.MdPseudoCheckboxModule,
              i12.MdPseudoCheckboxModule,([] as any[])),i0.ɵmpd(512,i12.MdOptionModule,
              i12.MdOptionModule,([] as any[])),i0.ɵmpd(512,i33.PortalModule,i33.PortalModule,
              ([] as any[])),i0.ɵmpd(512,i20.OverlayModule,i20.OverlayModule,([] as any[])),
          i0.ɵmpd(512,i12.MdAutocompleteModule,i12.MdAutocompleteModule,([] as any[])),
          i0.ɵmpd(512,i12.StyleModule,i12.StyleModule,([] as any[])),i0.ɵmpd(512,i12.MdButtonModule,
              i12.MdButtonModule,([] as any[])),i0.ɵmpd(512,i12.MdButtonToggleModule,
              i12.MdButtonToggleModule,([] as any[])),i0.ɵmpd(512,i12.MdCardModule,
              i12.MdCardModule,([] as any[])),i0.ɵmpd(512,i12.MdChipsModule,i12.MdChipsModule,
              ([] as any[])),i0.ɵmpd(512,i21.ObserversModule,i21.ObserversModule,([] as any[])),
          i0.ɵmpd(512,i12.MdCheckboxModule,i12.MdCheckboxModule,([] as any[])),i0.ɵmpd(512,
              i22.A11yModule,i22.A11yModule,([] as any[])),i0.ɵmpd(512,i12.MdDialogModule,
              i12.MdDialogModule,([] as any[])),i0.ɵmpd(512,i12.MdIconModule,i12.MdIconModule,
              ([] as any[])),i0.ɵmpd(512,i12.MdDatepickerModule,i12.MdDatepickerModule,
              ([] as any[])),i0.ɵmpd(512,i34.CdkTableModule,i34.CdkTableModule,([] as any[])),
          i0.ɵmpd(512,i12.MdTableModule,i12.MdTableModule,([] as any[])),i0.ɵmpd(512,
              i12.MdExpansionModule,i12.MdExpansionModule,([] as any[])),i0.ɵmpd(512,
              i12.MdFormFieldModule,i12.MdFormFieldModule,([] as any[])),i0.ɵmpd(512,
              i12.MdLineModule,i12.MdLineModule,([] as any[])),i0.ɵmpd(512,i12.MdGridListModule,
              i12.MdGridListModule,([] as any[])),i0.ɵmpd(512,i12.MdInputModule,i12.MdInputModule,
              ([] as any[])),i0.ɵmpd(512,i12.MdListModule,i12.MdListModule,([] as any[])),
          i0.ɵmpd(512,i12.MdMenuModule,i12.MdMenuModule,([] as any[])),i0.ɵmpd(512,
              i12.MdSelectModule,i12.MdSelectModule,([] as any[])),i0.ɵmpd(512,i12.MdTooltipModule,
              i12.MdTooltipModule,([] as any[])),i0.ɵmpd(512,i12.MdPaginatorModule,
              i12.MdPaginatorModule,([] as any[])),i0.ɵmpd(512,i12.MdProgressBarModule,
              i12.MdProgressBarModule,([] as any[])),i0.ɵmpd(512,i12.MdProgressSpinnerModule,
              i12.MdProgressSpinnerModule,([] as any[])),i0.ɵmpd(512,i12.MdRadioModule,
              i12.MdRadioModule,([] as any[])),i0.ɵmpd(512,i12.MdSidenavModule,i12.MdSidenavModule,
              ([] as any[])),i0.ɵmpd(512,i12.MdSliderModule,i12.MdSliderModule,([] as any[])),
          i0.ɵmpd(512,i12.MdSlideToggleModule,i12.MdSlideToggleModule,([] as any[])),
          i0.ɵmpd(512,i12.MdSnackBarModule,i12.MdSnackBarModule,([] as any[])),i0.ɵmpd(512,
              i12.MdSortModule,i12.MdSortModule,([] as any[])),i0.ɵmpd(512,i12.MdTabsModule,
              i12.MdTabsModule,([] as any[])),i0.ɵmpd(512,i12.MdToolbarModule,i12.MdToolbarModule,
              ([] as any[])),i0.ɵmpd(512,i12.MaterialModule,i12.MaterialModule,([] as any[])),
          i0.ɵmpd(512,i14.BrowserAnimationsModule,i14.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i24.ɵba,i24.ɵba,([] as any[])),i0.ɵmpd(512,i24.FormsModule,i24.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i24.ReactiveFormsModule,i24.ReactiveFormsModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[])),
          i0.ɵmpd(256,i12.MD_MENU_DEFAULT_OPTIONS,{overlapTrigger:true,xPosition:'after',
              yPosition:'below'},([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvem0vTXlQcm9qZWN0cy9tZWFuNC9zcmMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS96bS9NeVByb2plY3RzL21lYW40L3NyYy9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
