/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.my-fab[_ngcontent-%COMP%] {\n  position: absolute;\n  color: white;\n  background-color: rgba(#583123,1);\n  left: 20px;\n  top: 20px;\n  &.bars {\n    position: relative;\n  }\n}\n\n.my-toolbar[_ngcontent-%COMP%] {\n  padding: 0px;\n  .my-toolbar-row {\n    padding: 10px;\n    transition: 0.3s linear;\n    &:hover {\n      transition: 0.3s linear;\n      background-color: white;\n      color: #583123;\n      border: 4px #583123 solid;\n      border-left: none;\n      cursor: pointer;\n    }\n  }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvem0vTXlQcm9qZWN0cy9tZWFuNC9zcmMvYXBwL2NvbXBvbmVudHMvcHJvZHVjdGlvbi9wcm9kdWN0aW9uLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvem0vTXlQcm9qZWN0cy9tZWFuNC9zcmMvYXBwL2NvbXBvbmVudHMvcHJvZHVjdGlvbi9wcm9kdWN0aW9uLmNvbXBvbmVudC5zY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
