/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/app-routing.module';
import * as i2 from './components/create-stock/create-stock.component.ngfactory';
import * as i3 from './components/main-stock/main-stock.component.ngfactory';
import * as i4 from './components/catalog/catalog.component.ngfactory';
import * as i5 from './components/production/production.component.ngfactory';
import * as i6 from './components/stock/stock.component.ngfactory';
import * as i7 from '@angular/router';
import * as i8 from '@angular/common';
import * as i9 from '../../../src/app/components/create-stock/create-stock.component';
import * as i10 from '../../../src/app/components/main-stock/main-stock.component';
import * as i11 from '../../../src/app/components/catalog/catalog.component';
import * as i12 from '../../../src/app/components/production/production.component';
import * as i13 from '../../../src/app/components/stock/stock.component';
export const AppRoutingModuleNgFactory:i0.NgModuleFactory<i1.AppRoutingModule> = i0.ɵcmf(i1.AppRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.CreateStockComponentNgFactory,i3.MainStockComponentNgFactory,i4.CatalogComponentNgFactory,
              i5.ProductionComponentNgFactory,i6.StockComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(5120,i7.ActivatedRoute,i7.ɵf,[i7.Router]),i0.ɵmpd(4608,
          i7.NoPreloading,i7.NoPreloading,([] as any[])),i0.ɵmpd(6144,i7.PreloadingStrategy,
          (null as any),[i7.NoPreloading]),i0.ɵmpd(135680,i7.RouterPreloader,i7.RouterPreloader,
          [i7.Router,i0.NgModuleFactoryLoader,i0.Compiler,i0.Injector,i7.PreloadingStrategy]),
          i0.ɵmpd(4608,i7.PreloadAllModules,i7.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,
              i0.NgProbeToken,() => {
                return [i7.ɵb()];
              },([] as any[])),i0.ɵmpd(4608,i7.ɵg,i7.ɵg,[i0.Injector]),i0.ɵmpd(5120,
              i0.APP_INITIALIZER,(p0_0:any) => {
                return [i7.ɵh(p0_0)];
              },[i7.ɵg]),i0.ɵmpd(5120,i7.ROUTER_INITIALIZER,i7.ɵi,[i7.ɵg]),i0.ɵmpd(5120,
              i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
                return [p0_0];
              },[i7.ROUTER_INITIALIZER]),i0.ɵmpd(1024,i7.ɵa,i7.ɵd,[[3,i7.Router]]),
          i0.ɵmpd(512,i7.UrlSerializer,i7.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i7.ChildrenOutletContexts,i7.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,
              i7.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i8.LocationStrategy,
              i7.ɵc,[i8.PlatformLocation,[2,i8.APP_BASE_HREF],i7.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i8.Location,i8.Location,[i8.LocationStrategy]),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i7.ROUTES,() => {
            return [[{path:'',redirectTo:'/create',pathMatch:'full'},{path:'create',
                component:i9.CreateStockComponent},{path:'main',component:i10.MainStockComponent},
                {path:'catalog',component:i11.CatalogComponent},{path:'production',
                    component:i12.ProductionComponent},{path:'stock',component:i13.StockComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i7.Router,i7.ɵe,[i0.ApplicationRef,i7.UrlSerializer,
              i7.ChildrenOutletContexts,i8.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i7.ROUTES,i7.ROUTER_CONFIGURATION,[2,i7.UrlHandlingStrategy],
              [2,i7.RouteReuseStrategy]]),i0.ɵmpd(512,i7.RouterModule,i7.RouterModule,
              [[2,i7.ɵa],[2,i7.Router]]),i0.ɵmpd(512,i1.AppRoutingModule,i1.AppRoutingModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvem0vTXlQcm9qZWN0cy9tZWFuNC9zcmMvYXBwL2FwcC1yb3V0aW5nLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3ptL015UHJvamVjdHMvbWVhbjQvc3JjL2FwcC9hcHAtcm91dGluZy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
