/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvem0vTXlQcm9qZWN0cy9tZWFuNC9zcmMvYXBwL2NvbXBvbmVudHMvY2F0YWxvZy9jYXRhbG9nLWZvcm0vY2F0YWxvZy1mb3JtLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvem0vTXlQcm9qZWN0cy9tZWFuNC9zcmMvYXBwL2NvbXBvbmVudHMvY2F0YWxvZy9jYXRhbG9nLWZvcm0vY2F0YWxvZy1mb3JtLmNvbXBvbmVudC5zY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
