/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.my-fab[_ngcontent-%COMP%] {\n  position: absolute;\n  color: white;\n  background-color: rgba(#583123,1);\n  left: 20px;\n  top: 20px;\n  &.bars {\n    position: relative;\n  }\n}\n\n.my-toolbar[_ngcontent-%COMP%] {\n  padding: 0px;\n  .my-toolbar-row {\n    padding: 10px;\n    transition: 0.3s linear;\n    &:hover {\n      transition: 0.3s linear;\n      background-color: white;\n      color: #583123;\n      border: 4px #583123 solid;\n      border-left: none;\n      cursor: pointer;\n    }\n  }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvem0vTXlQcm9qZWN0cy9tZWFuNC9zcmMvYXBwL2NvbXBvbmVudHMvc3RvY2svc3RvY2suY29tcG9uZW50LnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS96bS9NeVByb2plY3RzL21lYW40L3NyYy9hcHAvY29tcG9uZW50cy9zdG9jay9zdG9jay5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
